### ISSUE TITLE
Use linked pane/tab to compare versions and translations.

### ISSUE THREAD

**Issue by noliaphyta** [AnthropologieBiblique/ObsidianTheologicalStudies#1]
>Hopefully one day a contributor will create a plugin which will allow synchronizing the scroll between these different views !

Obsidian natively supports synchronized scrolling with this feature, I never thought it was useful because I use Live Preview and I didn't need a live updating reading tab... but now I can see how important it is!

https://help.obsidian.md/User+interface/Workspace/Panes/Linked+pane

**Comment by Limezy** [comment]
Hi @noliaphyta, many thanks for your contribution.
Unfortunately, the linked pane function only works between two views of the *same note*, one being in edit mode, the other being in reading mode. What would be very nice is to be able to sync the scroll between two *different notes*, with a sync being line to line or header to header

**Comment by noliaphyta** [comment]
You're right, nevermind :( 
I blame romance languages being similar to Latin for not noticing, sorry...

Turns out linked panes are still useless. I didn't notice it because you can link different files and it appears to work, right until you start to scroll and they both become the same. 

Anyways, thanks for sharing such an amazing project, it's such great inspiration for using obsidian to study multiple reference sources!

---

I am now also annoyed that this plugin/function does not exist yet. I did a very quick search to see if there exists a solution. There is something called synchronous scrolling for some Microsoft Office applications and "scrollbind" for vim text editor. And there is also https://stackoverflow.com/questions/48365826/how-to-simultaneously-scroll-two-windows for an awful way to scroll on two windows at once. Maybe electron apps like obsidian have some way to implement this easily, but I don't think anyone made that feature request before.

**Comment by Limezy** [comment]
There is this discussion in the forum : https://forum.obsidian.md/t/synchronise-the-scroll-position-of-two-different-files/6569
I believe it's technically doable, but clearly out of my league (I'm far from being a dev). For some reason that feature doesn't seem to appeal a lot of users.

**Comment by noliaphyta** [comment]
Came across this new epub reader that reminded me of parallel reading! And it reminded me that I still have yet to read any of the French books I wanted to... I have yet to try it myself, it doesn't look very smooth on their website. Thought I would share.

https://github.com/readest/readest
https://readest.com/#parallel-read
