### ISSUE TITLE
Available on Obsidian Publish, or hosted anywhere?

### ISSUE THREAD

**Issue by TSSlade** [AnthropologieBiblique/ObsidianTheologicalStudies#2]
My father and sister-in-law are pastors, and I think Obsidian might be of interest to them. Neither of them are devs, though, so sending them to GitHub and asking them to clone a repo and then`{whatever is next}` is not going to be a successful way to introduce them to this wonderful resource.

Is this vault published online anywhere? Alternatively, are there any video demos/walkthroughs to which I could link?

**Comment by Limezy** [comment]
Hi @TSSlade and sorry for that very late reply. I definitely plan to do a video walkthrough when I'll have time.

Meanwhile, this vault isn't published online anywhere, but there is no need to clone any repo. Just download the code from https://github.com/AnthropologieBiblique/ObsidianTheologicalStudies/archive/refs/heads/main.zip, unzip it and open it as a vault in Obsidian (and activate extensions when prompted to do so)

**Comment by TSSlade** [comment]
Thanks for letting me know, @Limezy ! I appreciate the guidance.
